php:
  risky: true
  preset: recommended
  enabled:
    - alpha_ordered_traits
    - concat_with_spaces
    - laravel_braces
    - method_argument_space
    - method_chaining_indentation
    - no_single_line_asterisk_comment
    - not_operator_with_successor_space
    - phpdoc_trim_consecutive_blank_line_separation
    - single_line_comment_spacing
    - short_list_syntax
  disabled:
    - concat_without_spaces
    - method_argument_space_strict
    - new_with_braces
    - phpdoc_summary
    - unary_operators_spaces
  finder:
    exclude:
      - "node_modules"
      - "storage"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - "_ide_helper.php"
